
#' Plot compensation analysis
#' 
#' Plots the effect of varying compensation from 0 to 1 for each cell subclass,
#' examining the minimum subclass output result following a call to
#' [deconvolute()]. For this function to work, the argument `plot_comp` must be
#' set to `TRUE` during the call to [deconvolute()].
#' 
#' @param x An object of class 'deconv' generated by [deconvolute()].
#' @param ... Optional graphical arguments passed to [plot()].
#' @return No return value, plots the effect of varying compensation on minimum
#'   subclass output for each cell subclass.
#' @export

plot_comp <- function(x, ...) {
  if (inherits(x, "deconv")) {
    x <- x$comp_check
    if (is.null(x)) stop("missing comp_check analysis")
  }
  n <- length(x) -1
  px <- x$px
  x <- x[1:n]
  yr <- range(x)
  scheme <- hue_pal(h = c(0, 270), c = 120)(n)
  plot(NA, las = 1, xlim = c(0, 1), ylim = yr,
       xlab = "Compensation", ylab = "min output", ...)
  abline(h = 0)
  for (i in seq_len(n)) {
    lines(px, x[[i]], col = scheme[i])
  }
}
