
#' Gene signature heatmap
#' 
#' Produces a heatmap of genes signatures for each cell subclass using
#' ComplexHeatmap.
#' 
#' @param x Either a gene signature matrix with genes in rows and cell
#'   subclasses in columns, an object of S3 class 'cellMarkers' generated by
#'   [cellMarkers()], or an object of class 'deconv' generated by
#'   [deconvolute()].
#' @param type Either "subclass" or "group" specifying whether to show the cell
#'   subclass or cell group signature from a 'cellMarkers' or 'deconv' object.
#' @param use_filter Logical whether to show denoised gene signature.
#' @param rank Either "max" or "angle" controlling whether genes (rows) are
#'   ordered in the heatmap by max expression (the default) or lowest angle
#'   (a measure of specificity of the gene as a cell marker).
#' @param col Vector of colours passed to [ComplexHeatmap::Heatmap()].
#' @param ... Optional arguments passed to [ComplexHeatmap::Heatmap()].
#' @returns A 'Heatmap' class object.
#' @importFrom grDevices hcl.colors
#' @importFrom grid gpar
#' @importFrom ComplexHeatmap Heatmap
#' @export

signature_heatmap <- function(x,
                              type = c("subclass", "group"),
                              use_filter = NULL,
                              rank = c("max", "angle"),
                              col = rev(hcl.colors(10, "Greens3")),
                              ...) {
  rank <- match.arg(rank)
  type <- match.arg(type)
  cell_table <- NULL
  if (inherits(x, "deconv")) {
    x <- x$mk
    if (is.null(use_filter)) use_filter <- x$call$use_filter
  }
  if (inherits(x, "cellMarkers")) {
    if (is.null(use_filter)) use_filter <- TRUE
    if (type == "group") {
      gene_signature <- if (use_filter) {x$genemeans_filtered[x$group_geneset, ]
      } else x$genemeans[x$group_geneset, ]
      cell_table <- x$cell_table
    } else {
      gene_signature <- if (use_filter) {x$genemeans_filtered[x$geneset, ]
      } else x$genemeans[x$geneset, ]
      cell_table <- x$cell_table
    }
  } else {
    gene_signature <- x
  }
  whmax <- max.col(gene_signature)
  if (rank == "max") {
    rmax <- rowMaxs(gene_signature)
    ord <- order(whmax, -rmax)
  } else {
    ord <- seq_len(nrow(gene_signature))
  }
  rs <- cell_table[whmax]
  Heatmap(gene_signature,
          cluster_rows = FALSE,
          row_order = ord, row_split = rs,
          cluster_columns = FALSE, column_split = cell_table,
          cluster_column_slices = FALSE,
          column_title_gp = gpar(fontsize = 6),
          row_names_gp = gpar(fontsize = 6),
          column_names_rot = 75, column_names_gp = gpar(fontsize = 6),
          row_title_gp = gpar(fontsize = 6),
          col = col,
          heatmap_legend_param = list(title='mean'), ...)
}
