
#' Gene signature heatmap
#' 
#' Produces a heatmap of genes signatures for each cell subclass using
#' ComplexHeatmap.
#' 
#' @param x Either a gene signature matrix with genes in rows and cell
#'   subclasses in columns, or an object of S3 class 'cellMarkers' generated by
#'   [cellMarkers()].
#' @param col Vector of colours passed to [ComplexHeatmap::Heatmap()].
#' @param ... Optional arguments passed to [ComplexHeatmap::Heatmap()].
#' @returns A 'Heatmap' class object.
#' @importFrom grDevices hcl.colors
#' @importFrom grid gpar
#' @importFrom ComplexHeatmap Heatmap
#' @export

signature_heatmap <- function(x,
                              col = rev(hcl.colors(10, "Greens3")),
                              ...) {
  if (inherits(x, "cellMarkers")) {
    gene_signature <- x$genemeans_filtered[x$geneset, ]
    cell_table <- x$cell_table
  } else {
    gene_signature <- x
    cell_table <- NULL
  }
  whmax <- max.col(gene_signature)
  rmax <- rowMaxs(gene_signature)
  ord <- order(whmax, -rmax)
  rs <- cell_table[whmax]
  Heatmap(gene_signature,
          cluster_rows = FALSE,
          row_order = ord, row_split = rs,
          cluster_columns = FALSE, column_split = cell_table,
          cluster_column_slices = FALSE,
          column_title_gp = gpar(fontsize = 6),
          row_names_gp = gpar(fontsize = 6),
          column_names_gp = gpar(fontsize = 6),
          row_title_gp = gpar(fontsize = 6),
          col = col,
          heatmap_legend_param = list(title='mean'), ...)
}
